config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  #get 'users/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :date, presence: true
  validates :distance, presence: true, length: { maximum: 50 }
  validates :time, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of a given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    #generates a random string of 22 characters each one with 64 possibilities
    SecureRandom.urlsafe_base64 
  end
  
  # Remembers a user in the database for use in the persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forget a user
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
    private
      
      # Confirms a logged in user
      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your data has successfully been uploaded"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  def destroy
    # @post.destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  
    def post_params
      params.require(:post).permit(:date, :time, :distance)
    end
  
    # def correct_user
    #   @post = current_user.posts.find_by(id: params[:id])
    #   redirect_to root_url if @post.nil?
    # end
  
    def correct_user
      redirect_to root_url unless current_user.admin? || current_user.posts.find_by(id: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log in the user and redirect to profile page
      log_in user
      
      if params[:session][:remember_me] == '1'
        remember(user)
      else
        forget(user)
      end
      redirect_back_or user
      #remember user
      #redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @post = current_user.posts.build if logged_in?
  end

  def help
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_or_manager_user, only: :destroy
  # before_action :manager_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to YourFitnessTracker!"
      #handle a save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    # this line only pulls the releant user out of the database
    # @user = User.find(params[:id]) #this step is done in the correct_user before filter
  end
  
  def update
    if @user.update(user_params)
      #update the user with the new data
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # Before filters
    
    # Confirms a correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user
    def admin_or_manager_user
      redirect_to(root_url) unless (current_user.admin? || current_user.manager?)
    end
    
    # def manager_user
    #   redirect_to(root_url) unless current_user.manager?
    # end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title
  def full_title(page_title = '')
    base_title = "YourFitnessTracker"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns the user corepsonding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user && user == current_user
  end
  
  # Redirects to stored location or to the default
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  # Store the url trying to be accesed
  
  def store_location
    # get the url of the requested page
    # puts the url in the session variable under the key :forwarding_url
    session[:forwarding_url] = request.original_url if request.get?
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2022, YourFitnessTracker
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="logopic">
          <%= link_to image_tag("roundlogo.png", alt: "Jogging photo", width: "30"), root_path %>
        </div>
        <%= link_to "YourFitnessTracker", root_path, id: "logo" %>
        <nav>
          
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          
          <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to gravatar_for(post.user, size: 50), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="date"><%= post.date %></span>
  <span class="distance">Distance: <%= post.distance %> km</span>
  <span class="time">Duration: <%= post.time %> &nbsp [h/min/sec]</span>
  <% dt = DateTime.parse(post.time) %>
  <% seconds = dt.hour*3600 + dt.min*60 %>
  <% distance_float = post.distance.to_f * 1000 %>
  <% avg_speed = distance_float / seconds %>
  <% avg = avg_speed.truncate(2) %>
  <span class="average">Average speed: <%= avg %> &nbsp [m/sec]</span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) || current_user.admin? %>
      <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.date_field :date %>
    <%= f.text_field :distance, placeholder: "Distance [km]" %>
    <%= f.text_field :time, placeholder: "How long were you running? [h:mm:ss]" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 120), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span class="post_count"><%= pluralize(current_user.posts.count, "post") %></span>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

  <!--<h3>Contact us at </h3>-->
  <p>Follow us on <a href="https://www.instagram.com/ebita.ro/">Instagram</a></p>
  <p>Our <a href="https://www.instagram.com/ebita.ro/">facebook</a> page</p>
  <p>Call us: <a href="https://www.instagram.com/ebita.ro/">0775283255</a></p>
  <p>Email us at: <a href="https://www.instagram.com/ebita.ro/">tracker_support@gmail.com</a></p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  <p>Got any problems? Colsult our Frequently Asked Questions section here: <a href="https://www.instagram.com/ebita.ro/">FAQ</a></p>
  <p>Didn't solve your proglem?</p>
  <p>Get in touch with us now! </p>
  <%= link_to "Contact page", contact_path %>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info'%>
            </section>
            <h4>Register a new running session:</h4>
            <section class="post_form">
                <%= render 'shared/post_form' %>
            </section>
        </aside>
        
        <div class="col">
            <h1>Keep On Running</h1>
            <!--link_to image_tag("keeponrunning.jpg", alt: "Keep running", width: "600") %>-->
        </div>
    
    </div>
<% else %>
    <div class="center jumbotron">
        <h1>Jogging time tracker</h1>
        <h2>
            The best app for tracking your favourite sport activity.
        </h2>
        <div class="photos">
            <%= image_tag("rounded.png", alt: "Jogging photo", width: "900") %>
        </div>
    
        <div class="content1">
            <h2>Track your runs</h2>
        </div>
    
        <p>You don't have an account?</p>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    
    </div>

    <p>Keep a record of your jogging times, distances and more..</p>
    <br>
    <li><p>Follow us on <a href="https://www.instagram.com/ebita.ro/">Instagram</a></p></li>
    <li><p>Our <a href="https://www.instagram.com/ebita.ro/">facebook</a> page</p></li>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'%>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user%>
      <% if ( current_user.admin? || current_user.manager? ) && !current_user?(user) && !user.admin? %>
        | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @user, local: true) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, size: 120 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
    <div class="col-md-8">
      <% if @user.posts.any? %>
        <h3>Running sessions (<%= @user.posts.count %>)</h3>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>
    </div>
</div>